<?php

namespace App\Services;

use App\Models\Site;
use Illuminate\Support\Facades\Storage;

/**
 * Generates a SITE.md snapshot for a given site from DB data only,
 * then persists it to storage/app/sites/{id}/SITE.md.
 *
 * This file is the sole context source for AI Agent Mode — no SSH,
 * no live DB queries at chat time.
 */
class SiteMdService
{
    public function generate(Site $site): string
    {
        $site->loadMissing(['server', 'client', 'sitemeta', 'plugins', 'themes']);

        $lines = [];

        // ── Header ────────────────────────────────────────────────────────────
        $lines[] = '# Site Snapshot: ' . $site->name;
        $lines[] = '> Auto-generated by WPGrip. Last updated: ' . now()->toDateTimeString() . ' UTC';
        $lines[] = '';

        // ── Core info ─────────────────────────────────────────────────────────
        $lines[] = '## Site';
        $lines[] = '| Field | Value |';
        $lines[] = '|---|---|';
        $lines[] = '| Name | ' . ($site->name ?? 'n/a') . ' |';
        $lines[] = '| URL | ' . ($site->url ?? 'n/a') . ' |';
        $lines[] = '| Status | ' . ($site->status?->value ?? 'n/a') . ' |';
        $lines[] = '| WordPress version | ' . ($site->wp_ver ?? 'n/a') . ' |';
        $lines[] = '| PHP version | ' . ($site->php_ver ?? 'n/a') . ' |';
        $lines[] = '| WP-CLI version | ' . ($site->cli_ver ?? 'n/a') . ' |';
        $lines[] = '| DB prefix | ' . ($site->db_prefix ?? 'n/a') . ' |';
        $lines[] = '| Directory path | ' . ($site->dir_path ?? 'n/a') . ' |';
        $lines[] = '| Directory size | ' . ($site->dir_size ? $site->dir_size . ' MB' : 'n/a') . ' |';
        $lines[] = '| SSH user | ' . ($site->ssh_user ?? 'n/a') . ' |';
        $lines[] = '| SSH connected | ' . ($site->ssh_connection ? 'yes' : 'no') . ' |';
        $lines[] = '| Is staging | ' . ($site->is_staging ? 'yes' : 'no') . ' |';
        $lines[] = '| Backup enabled | ' . ($site->backup_enabled ? 'yes' : 'no') . ' |';
        $lines[] = '| Last synced | ' . ($site->last_sync ? (is_string($site->last_sync) ? $site->last_sync : $site->last_sync->toDateTimeString()) : 'never') . ' |';
        $lines[] = '';

        // ── Server ────────────────────────────────────────────────────────────
        if ($site->server) {
            $s = $site->server;
            $lines[] = '## Server';
            $lines[] = '| Field | Value |';
            $lines[] = '|---|---|';
            $lines[] = '| Name | ' . $s->name . ' |';
            $lines[] = '| IP | ' . $s->ip . ' |';
            $lines[] = '| SSH Port | ' . ($s->port ?? 22) . ' |';
            $provider = $s->provider;
            $lines[] = '| Provider | ' . ($provider instanceof \BackedEnum ? $provider->value : ($provider ?? 'n/a')) . ' |';
            $lines[] = '';
        }

        // ── Client ────────────────────────────────────────────────────────────
        if ($site->client) {
            $lines[] = '## Client';
            $lines[] = 'Name: ' . $site->client->name;
            $lines[] = '';
        }

        // ── Site Meta ─────────────────────────────────────────────────────────
        if ($site->sitemeta) {
            $meta    = $site->sitemeta;
            $lines[] = '## Site Meta';
            $lines[] = '| Field | Value |';
            $lines[] = '|---|---|';
            $lines[] = '| DB size | ' . ($meta->db_size ? $meta->db_size . ' MB' : 'n/a') . ' |';
            $lines[] = '| Domain expiry | ' . ($meta->domain_expiry_date ?? 'n/a') . ' |';
            $lines[] = '| Active theme | ' . ($meta->active_theme ?? 'n/a') . ' |';
            $lines[] = '| Vulnerable | ' . ($meta->is_vulnerable ? 'YES ⚠️' : 'no') . ' |';
            $lines[] = '| Has issues | ' . ($meta->has_issues ? 'YES ⚠️' : 'no') . ' |';
            if ($meta->issues) {
                $lines[] = '| Issues | ' . $meta->issues . ' |';
            }
            $lines[] = '';

            // DB tables
            if ($meta->db_tables) {
                $tables = is_string($meta->db_tables) ? json_decode($meta->db_tables, true) : $meta->db_tables;
                if (is_array($tables) && count($tables)) {
                    $lines[] = '### Database Tables (' . count($tables) . ' total)';
                    foreach ($tables as $t) {
                        $name = $t['Name'] ?? ($t['name'] ?? '?');
                        $size = $t['Size'] ?? ($t['size'] ?? '?');
                        $lines[] = '- `' . $name . '` — ' . $size;
                    }
                    $lines[] = '';
                }
            }
        }

        // ── Plugins ───────────────────────────────────────────────────────────
        if ($site->plugins && $site->plugins->count()) {
            $plugins        = $site->plugins;
            $withUpdates    = $plugins->filter(fn ($p) => !empty($p->pivot->update_version));
            $active         = $plugins->filter(fn ($p) => ($p->pivot->status ?? '') === 'active');
            $inactive       = $plugins->filter(fn ($p) => ($p->pivot->status ?? '') !== 'active');

            $lines[] = '## Plugins';
            $lines[] = '- Total: ' . $plugins->count();
            $lines[] = '- Active: ' . $active->count();
            $lines[] = '- Inactive: ' . $inactive->count();
            $lines[] = '- Updates available: ' . $withUpdates->count();
            $lines[] = '';

            if ($withUpdates->count()) {
                $lines[] = '### Plugins With Pending Updates';
                foreach ($withUpdates as $p) {
                    $lines[] = '- **' . $p->name . '** v' . ($p->pivot->version ?? '?') . ' → v' . $p->pivot->update_version;
                }
                $lines[] = '';
            }

            $lines[] = '### All Plugins';
            $lines[] = '| Plugin | Version | Status | Update |';
            $lines[] = '|---|---|---|---|';
            foreach ($plugins as $p) {
                $upd = $p->pivot->update_version ? '→ v' . $p->pivot->update_version : '-';
                $lines[] = '| ' . $p->name . ' | ' . ($p->pivot->version ?? 'n/a') . ' | ' . ($p->pivot->status ?? 'n/a') . ' | ' . $upd . ' |';
            }
            $lines[] = '';
        }

        // ── Themes ────────────────────────────────────────────────────────────
        if ($site->themes && $site->themes->count()) {
            $lines[] = '## Themes';
            $lines[] = '| Theme | Version | Update |';
            $lines[] = '|---|---|---|';
            foreach ($site->themes as $t) {
                $upd = $t->pivot->update_version ? '→ v' . $t->pivot->update_version : '-';
                $lines[] = '| ' . $t->name . ' | ' . ($t->pivot->version ?? 'n/a') . ' | ' . $upd . ' |';
            }
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Regenerate and persist SITE.md for the given site.
     * Returns the path relative to the storage disk root.
     */
    public function write(Site $site): string
    {
        $content = $this->generate($site);
        $path    = 'sites/' . $site->id . '/SITE.md';

        Storage::disk('local')->put($path, $content);

        return $path;
    }

    /**
     * Read the persisted SITE.md content, or generate on-the-fly if missing.
     */
    public function read(Site $site): string
    {
        $path = 'sites/' . $site->id . '/SITE.md';

        if (Storage::disk('local')->exists($path)) {
            return Storage::disk('local')->get($path);
        }

        // First-time fallback: generate now and cache it
        $this->write($site);
        return Storage::disk('local')->get($path);
    }
}
